### PR TITLE
Add (encrypted) Snyk token to travis configuration

### PR DESCRIPTION
**Pull request by hedgepigdaniel**
Since it is not currently working due to billing issues (this confuses me because its meant to be "Free for open source")

### CODE REVIEW

**Comment by chapati23** [comment]
Not sure this is the right forum for discussion but just wanted to throw in that we used snyk for a long time, but recently cancelled our subscription and simply started using `yarn audit` which doesn't require any extra tooling.

Can I ask what features you're getting from `snyk` that `yarn audit` doesn't provide?

**Comment by hedgepigdaniel** [comment]
Interesting, I didn't know it existed. Is it possible to easily ignore certain issues with `yarn audit`? There are a couple that snyk currently identifies with no easy fix and also very low risk - see https://github.com/respond-framework/rudy/blob/master/.snyk

I was thinking of trying some of the alternatives here at some point: https://developers.redhat.com/blog/2017/04/12/using-snyk-nsp-and-retire-js-to-identify-and-fix-vulnerable-dependencies-in-your-node-js-applications/

**Comment by chapati23** [comment]
Ignoring vulnerabilities is probably a bit harder currently with `npm|yarn audit`.

For the alternatives: nsp has been acquired by npm recently, i'd bet that `yarn audit`, `npm audit` and `snyk` all access the same data. Maybe snyk has _some_ extra data that they maintain themselves but I'd be surprised if it was a substantial amount.

image

There's two npm packages i found that aim to build a bit of extra functionality on top of `npm|yarn audit`:

1. https://www.npmjs.com/package/npm-audit-resolver
1. https://www.npmjs.com/package/better-npm-audit

There's also the `yarn audit --json` flag that will return the result in json format so you could apply your own logic to ignore certain deps. Admittedly that would add extra work.

**Comment by ScriptedAlchemy** [comment]
Do we want this token exposed? I can set it as an environment variable within travis so its hidden. I usually put github and npm tokens in side travisCI's environment variable section

**Comment by ScriptedAlchemy** [comment]
image

**Comment by hedgepigdaniel** [comment]
I think what I've done here is basically the same thing - the value in the travis configuration is encrypted.

Since I made the PR, I learned that Snyk is indeed free for open source, but you have to explicitly mark each repository as open source in their UI. I've done that, so it should keep working now.

**Pull request merged**
