### PR TITLE
refactor(transformations): Various changes, documentation

### PR DESCRIPTION
**Pull request by hedgepigdaniel**
- Add isolated unit tests for urlToAction and actionToUrl and their dependencies
- Perform URL encoding and decoding between the URL and `toPath`/`fromPath`, so that they do not have to deal with it.
- Change the URL side of `fromPath`/`toPath` to receive arrays for multi segment paths. This allows slashes to be encoded correctly inside segments.
- Redirect to a 404 page it `toPath` or `fromPath` throws, instead of crashing
- Implement default `fromPath` and `toPath` to match the existing behaviour, except for
   - `null` is converted to `undefined` in `toPath`
   - `toPath` throws if inappropriate types are passed into `params`
- Configure eslint to be happy about test globals in test files
- Some flow type errors were fixed on the way

### CODE REVIEW

**Comment by faceyspacey** [comment]
What's the thinking behind removing the encoding/decoding? To make it easier for advanced users that just rather do it themselves? 

The purpose is to have solid defaults so you don't have to fiddle with this until you really have to. Without this, everyone has to provide `options.toPath` and `options.fromPath` to insure basic encoding/decoding.

I'm fine with whatever you guys are doing over here. I'm just wondering what the counter argument is in case I missed something??


Here's the new docs for `to/fromPath`. It explains the purpose behind the "reverse symmetry" of `encodedVal`, which only matters to those that wanna customize it:


## Transformations 

### `to/fromPath(value, key): string`

To customize the param transformation into how you want your app to see it, here's how the date from above could be handled:

```js
POST: {
  path: '/post/:slug/:date',
  fromPath: (val, key) => key === 'date' ? new Date(val) : val
  toPath: (val, key) => {
    if (key === 'date') {
      const month = numToMonth(val.getMonth())
      const day = val.getUTCDate()
      const year = val.getFullYear()

      return `${month}-${day}-${year}`
    }

    return value
  }
},
```

Notice you are passed each param one by one, where the `key` is the name of the param.

## Custom encoding/decoding

### `to/fromPath(value, key, encodedVal): string`

```js
POST: {
  path: '/post/:slug',
  fromPath: (val, key, encodedVal) => decodeURIComponent(encodedVal)
  toPath: (val, key, encodedVal) => encodeURIComponent(val)
},
```

The 1st argument, `val`, in both functions is the *application-ready* version of the path segment, decoded with `decodeURIComponent` prior to being passed to `fromPath`.

The 3rd argument, `encodedVal`, in both functions is the *URL-ready* version of the path segment, encoded with `encodeURIComponent` prior to being passed to `toPath`.

If you'd like to perform your own custom encoding/decoding, notice the reverse symmetry:

- **decode `encodedVal` in `fromPath`**
- **encode `val` in `toPath`**

That may seem odd, but keep in mind this *not* the primary use case. This is the "low level" approach. 

The primary use-case is automatic encoding/decoding performed internally by Respond, in which case it's easier to just think in terms of an already transformed value for `val`, as in the previous example.

**Comment by hedgepigdaniel** [comment]
Thanks for those docs, I'll incorporate them. I was actually thinking of adding the docs as I went.

The defaults are still there and it still works the same apart from fixing a bug. So there is still no need for users to provide `fromPath`/`toPath`.

The behaviour change in the default configuration is fixing `null` params being serialised as `'null'` (and accordingly, making it possible for `toPath` to return null to not include the parameter in the URL).

Re changing the signatures to remove `encodedVal`/`decodedVal`, I think its confusing to provide them at all when they are not necessarily correct or useful. For example in the default `fromPath`/`toPath` the treatment of slashes (i.e. not encoding them) is one example of where `encodedVal`/`decodedVal` would have been wrong/innapropriate (i.e., not URL ready). Given that encoding/decoding is as simple as calling `decodeURIComponent` or `encodeURIComponent`, I think it's less confusing for an advanced user who chooses to customise `fromPath`/`toPath` to do that than it would be for them to work out which argument is `encodedVal`/`decodedVal` and that that is not the one they want (a potential trap since the values would often be identical).

Related question: Whats the reason for the difference in the treatment of `convertNumbers` and `capitalizedWords` in the route transformations vs the global transformations? It looks like if transformations are provided on the route, they cause the number and capitalization transformations to be skipped, whereas the transformations in the global options are only called after the number/capitalization transforms occur.

**Comment by faceyspacey** [comment]
> less confusing for an **advanced user** 

Exactly. It's confusing for new and intermediate developers, which, like a bell curve, will be the bulk of developers. They shouldn't have to think about encoding/decoding. Me personally, I only got a hold of those de/encoding functions (and their counterparts that do the whole URL) while building Rudy.

The above doc makes the lesser used advanced case as clear as can be.

If the default case, i.e. the first arg `val` needs to be improved, we should do that. 

----
> Related question: Whats the reason for the difference in the treatment of convertNumbers and capitalizedWords in the route transformations vs the global transformations? It looks like if transformations are provided on the route, they cause the number and capitalization transformations to be skipped, whereas the transformations in the global options are only called after the number/capitalization transforms occur.

I'm actually not sure what you mean. If you can paste the exact code ur referring to, i can answer your question.

**Comment by faceyspacey** [comment]
Oh, I see...

**Comment by faceyspacey** [comment]
The thinking is so that individual routes can override the `options.to/fromPath`.

In all cases, you don't get to mix `convertNumbers` + `capitalizedWords` with to/fromPath.

**Comment by hedgepigdaniel** [comment]
Well the default and probably most common case is to not customise fromPath/toPath at all, and I haven't changed that here

**Comment by hedgepigdaniel** [comment]
So then it should probably call toPath/fromPath if provided, and skip the default transformations in both cases? That seems more concistent to me

**Comment by faceyspacey** [comment]
if what ur saying is having options level to/from overrides route level convertNumbers/capitalizedWords, I disagree.

For example, before deciding that route level and options level callbacks would be called in parallel, the original plan was to make it so that route level callbacks override the options level ones. ..But then I realized you could easily customize it to have this behavior in `shouldCall`. Its promoted as an alternate behavior in the upcoming docs:

```diff
options.shouldCall = (name, route, req) => {
  if (!route[name] && !req.options[name]) return false

  // skip callbacks (beforeEnter, thunk, etc) called on server, which produced initialState
  if (isHydrate(req) && !/onEnter|onError/.test(name)) return false

  // dont allow these client-centric callbacks on the server
  if (isServer() && /onEnter|Leave/.test(name)) return false

+  if (route[name]) return allowOnlyRoute
  return allowBoth
}

const allowBoth = { route: true, options: true }
+const allowOnlyRoute = { route: true, options: false }
```

So, it's more "consistent," but consistency isn't what we're going for. Customizability is what we're going for.

**Comment by faceyspacey** [comment]
> Well the default and probably most common case is to not customise fromPath/toPath at all, and I haven't changed that here

agreed that we gotta get this absolutely right before release of Respond Framework. My intuition has been that the default should be decoded/encoded, so basic things like spaces are properly handled:

`/path/this%20is%20a%20param/`

`{ type: 'FOO', params: { param: 'this is a param' } }`

Feel me. It's a common hurdle we should handle for users. 

The browser will add `%20` automatically to any spaces in a URL. So for that reason alone we gotta offer a default doing the encoding/decoding. Sure, if ur running a very tight shift and insure ur params have no words with spaces *from the start*, it's not a problem. If thats the boat ur in, its the same as me--i have preemptively thought of sluggification for a long time. But the assumption is many developers will dispatch params with spaces. It's very common. And I'd prefer not to be as preemptive as I've been in the past. I wanna as many sensible defaults as possible. Sensible defaults everywhere. Respond Framework isn't this completely customizable modular mess that has taken its toll on the javascript world. 

Things as "bare metal" as Redux had a time and place while we built up the new ecosystem. Now that we know what it looks like, it's time for opinions again, even at the expense of modularity at times. Here, u can still customize (aka, it's modularish/composeableish), but but we have *sensible defaults.*

**spaces my friend, not %20**

**Comment by hedgepigdaniel** [comment]
> My intuition has been that the default should be decoded/encoded, so basic things like spaces are properly handled

I'm not sure if there is any disagreement there... as I said I haven't changed that default behaviour?

**Comment by faceyspacey** [comment]
I'm just responding to this you said:

> **Well the default and probably most common case is to not customise fromPath/toPath at all**

If that's true, we wouldnt need 3 args. If it's untrue, we need 3 args--cuz of course no matter we gotta offer the *non customized* case.

**Comment by faceyspacey** [comment]
It's all good, do what u think. You answered my questions. Code is the real discussion anyway. I'll take what you have coded in mind.

**Comment by hedgepigdaniel** [comment]
Sure OK.

Btw, we changed that code you referred to here: https://github.com/respond-framework/rudy/pull/17/files

I think it makes more sense to configure options related to what callbacks to call in the call middlleware itself rather than with a global option - its not something that the rest of the code needs to know about, and clearer if the middleware is in control of it.


```javascript
   call('routeBeforeEnter', { includeOptions: false }),
```

**Comment by faceyspacey** [comment]
I like that api!

**Pull request merged**
