### PR TITLE
chore: update babel packages

### PR DESCRIPTION
**Pull request by hedgepigdaniel**
caniuse/browserslist actually stopped working with the previous versions :confused:

### CODE REVIEW

**Comment by ScriptedAlchemy** [comment]
What’s up with Babel-watch?

**Comment by hedgepigdaniel** [comment]
Well in my fork it still has a bug where it sometimes spawns ghost processes that eat CPU, and the original fork now seems to be somewhat maintained, so I'm hoping one of the recent changes fixed it: https://github.com/kmagiera/babel-watch/commits/master

**Comment by ScriptedAlchemy** [comment]
Is kmagiera the original author?

**Comment by hedgepigdaniel** [comment]
I'd say so: https://github.com/kmagiera/babel-watch/graphs/contributors

https://github.com/kmagiera/babel-watch/commit/144f105c4bd42a93e702c3031812bd726d462395

**Pull request merged**
