### PR TITLE
docs: add build command into hacking instructions

### PR DESCRIPTION
**Pull request by Guria**

### CODE REVIEW

**Comment by hedgepigdaniel** [comment]
Hi, Thanks!

I don't think the build command is necessary anymore to run the development server (since it should directly use the files in all the `src` directories, compiled only once with webpack.

Did you find that it was necessary for some reason?

**Comment by Guria** [comment]
Yes. I had to build it first to make it work

**Comment by hedgepigdaniel** [comment]
Right, yes I see what you mean.

I've opened this to fix the problem: https://github.com/respond-framework/rudy/pull/44

That should restore the intended behaviour (so the boilerplate always uses the up to date source).

**Comment by hedgepigdaniel** [comment]
Closing in favour of https://github.com/respond-framework/rudy/pull/44 which should solve the problem. Thanks for the heads up.

**Pull request closed without merging**
